# Builder stage
FROM node:21-bookworm
SHELL ["/bin/bash", "-c"]
RUN npm -g install pnpm && SHELL=bash pnpm setup && source /root/.bashrc && pnpm add -g pnpm
RUN pnpm add typescript tslib
WORKDIR /opt/app

ENV NODE_SCRIPT={{ agent.script }}
ENV GENERATE_SOURCEMAP=false
ENTRYPOINT npm run-script {{ agent.script }}
