FROM node:24-bookworm
SHELL ["/bin/bash", "-c"]
RUN yarn add typescript tslib
WORKDIR /app

COPY ./conf/ /conf/
COPY ./app/ /app/

RUN yarn install
RUN chmod a+x /conf/docker-entrypoint.sh

ENV DEBUG=*:*
ENTRYPOINT ["/conf/docker-entrypoint.sh"]
