# Builder stage
FROM node:lts-bookworm
SHELL ["/bin/bash", "-c"]
RUN yarn add typescript tslib
WORKDIR /opt/app

ENV NODE_SCRIPT={{ verifier.script }}
ENV GENERATE_SOURCEMAP=false
ENTRYPOINT npm run {{ verifier.script }}
