# Builder stage
FROM node:21-bookworm
SHELL ["/bin/bash", "-c"]
RUN yarn add typescript tslib
WORKDIR /opt/app

ENV NODE_SCRIPT={{ verifier.script }}
ENV GENERATE_SOURCEMAP=false
ENV DEBUG=*:*
ENTRYPOINT npm run {{ verifier.script }}
