# The list of installations defines the subpaths on the veramo-agent that the agent will listen to.
# The configuration for these installations is now maintained in an external repository
installations:
  - name: mbob
    hostname: mbob
    test:
      credential: SupportCredential
      object:
        sub:
          - "12"
        eduperson_unique_id:
          - "abracadabra"
        given_name:
          - "test"
        family_name:
          - "janssen"
        email:
          - "test@example.org"
    adminToken: "{{ tokens.mbob.admin }}"
    hasTokenEndpoint: true

  - name: mbobauth
    hostname: mbobauth
    test:
      as: true
      credential: InstitutionCardCredential
      object:
        given_name:
          - "test"
        family_name:
          - "janssen"
        email:
          - "test@example.org"
    adminToken: "{{ tokens.mbobauth.admin }}"
    hasTokenEndpoint: true

  - name: tun
    hostname: tun
#    test:
#      preauthcode: vG8T2WNVFGs0TSzx135XHDzNRWO3FFKM
#      credential: AcademicEnrollmentCredential
#      object:
#        sub:
#          - "12"
#        eduperson_unique_id:
#          - "abracadabra"
#        given_name:
#          - "test"
#        family_name:
#          - "janssen"
#        email:
#          - "test@example.org"
    adminToken: "{{ tokens.tun.admin }}"
    hasTokenEndpoint: true

  - name: uvh
    hostname: uvh
    test:
      credential: SupportCredential
      object:
        sub:
          - "12"
        eduperson_unique_id:
          - "abracadabra"
        given_name:
          - "test"
        family_name:
          - "janssen"
        email:
          - "test@example.org"
    adminToken: "{{ tokens.uvh.admin }}"
    hasTokenEndpoint: true

  - name: uvhauth
    hostname: uvhauth
    test:
      as: true
      credential: InstitutionCardCredential
      object:
        given_name:
          - "test"
        family_name:
          - "janssen"
        email:
          - "test@example.org"
    adminToken: "{{ tokens.uvhauth.admin }}"
    hasTokenEndpoint: true

  - name: hbot
    hostname: hbot
    test:
      credential: SupportCredential
      object:
        sub:
          - "12"
        eduperson_unique_id:
          - "abracadabra"
        given_name:
          - "test"
        family_name:
          - "janssen"
        email:
          - "test@example.org"
    adminToken: "{{ tokens.hbot.admin }}"
    hasTokenEndpoint: true

  - name: hbotauth
    hostname: hbotauth
    test:
      as: true
      credential: InstitutionCardCredential
      object:
        given_name:
          - "test"
        family_name:
          - "janssen"
        email:
          - "test@example.org"
    adminToken: "{{ tokens.hbotauth.admin }}"
    hasTokenEndpoint: true

  - name: nlgov
    hostname: nl.gov
    test:
      as: true
      credential: PID
      object:
        personal_administrative_number: "42"
        document_number: "1"
        given_name: "test"
        family_name: "janssen"
        nationality: "example"
    adminToken: "{{ tokens.nlgov.admin }}"
    hasTokenEndpoint: true

  - name: nbgov
    hostname: nb.gov
    test:
      as: true
      credential: PID
      object:
        personal_administrative_number: "42"
        document_number: "1"
        given_name: "test"
        family_name: "janssen"
        nationality: "example"
    adminToken: "{{ tokens.nbgov.admin }}"
    hasTokenEndpoint: true

  - name: epi
    hostname: epi
    test:
      as: true
      credential: eduID
      object:
        sub:
          - "12"
        eduperson_unique_id:
          - "abracadabra"
        given_name:
          - "test"
        family_name:
          - "janssen"
        email:
          - "test@example.org"
    adminToken: "{{ tokens.epi.admin }}"
    hasTokenEndpoint: true

  - name: sandbox
    hostname: sandbox
    test:
      credential: PID_JWT
      object:
        personal_administrative_number: "42"
        document_number: "1"
        given_name: "test"
        family_name: "janssen"
        nationality: "example"
    adminToken: "{{ tokens.sandbox.admin }}"
    hasTokenEndpoint: true
