# key refers to the alias of the verifier configured did keys
verifiers:
  - name: demovp
    path: "/demovp"
    testPresentation: PID

  - name: proxy
    path: "/proxy"
    testPresentation: ABC

  - name: sandbox
    path: "/sandbox"
    testPresentation: ABC
