# key refers to the alias of the verifier configured did keys
verifiers:
  - name: sandbox
    path: "/sandbox"
    testPresentation: ABC
    token: "{{ tokens.sandbox.verAdmin }}"
    oidfed:
      key: oidfed
      auth: https://intermediary.poc2.dev.oidf.lab.surfconext.nl
      ta: https://ta.poc2.dev.oidf.lab.surfconext.nl
      contact: info@eduwallet.nl
