# Statuslists
statuslists:
  enabled: true
  domain: "status.{{ deploydomain }}"
  dir: "{{ basedir }}/statuslist-agent"
  keytype: "Secp256r1"
  installations:
    - abcrevoke
    - aecrevoke
    - ietf
    - pidrevoke

