base_itb_data:
  abc:
    given_name: Martin
    family_name: Jørgensen
    name: Martin Jørgensen
    shac_home_organisation: mbob
    sub: mjorgensen
    eduperson_affiliation:
      - employee
      - member
    eduperson_scoped_affiliation:
      - employee@mbob.nl
      - member@mbob.nl
    eduperson_entitlement:
      - urn:mace:dir:entitlement:common-lib-terms-example
    eduperson_assurance:
      - https://refeds.org/assurance
      - https://refeds.org/assurance/IAP/high
      - https://refeds.org/assurance/IAP/local-enterprise
      - https://refeds.org/assurance/ATP/ePA-1m
    eduperson_unique_id: d29632ca63d10461fa3ddc400cb7f5089806a635
    email: mjorgensen@example.net
  gc:
    given_name: Test
    family_name: Tester

itb:
  enabled: true
  path: /opt/itb
  domain: itb.dev.eduwallet.nl
  project: eduwallet_itb
  port: 80
  postmaster: info@muisit.nl

  configurations:
    - name: ABC
      description: Direct issuance of an Academic Base Credential
      url: "{{ protocol }}:{{ basedomain }}/sandbox"
      token: "{{ tokens.sandbox.admin }}"
      data:
        credentials:
          - AcademicBaseCredential_JWT
        grants:
          "urn:ietf:params:oauth:grant-type:pre-authorized_code":
            "pre-authorized_code": generate
        credentialDataSupplierInput: "{{ base_itb_data.abc}}"         
        credentialMetadata:
          expiration: 2678400
    - name: ABC_TX
      description: Protected issuance of an Academic Base Credential
      url: "{{ protocol }}:{{ basedomain }}/sandbox"
      token: "{{ tokens.sandbox.admin }}"
      data:
        credentials:
          - AcademicBaseCredential_JWT
        grants:
          "urn:ietf:params:oauth:grant-type:pre-authorized_code":
            "pre-authorized_code": generate
            tx_code:
              code: 1234
              input_mode: numeric
              length: 4
              description: PIN
        credentialDataSupplierInput: "{{ base_itb_data.abc}}"         
        credentialMetadata:
          expiration: 2678400
    - name: ABC_TX2
      description: Protected issuance of an Academic Base Credential
      url: "{{ protocol }}:{{ basedomain }}/sandbox"
      token: "{{ tokens.sandbox.admin }}"
      data:
        credentials:
          - AcademicBaseCredential_JWT
        grants:
          "urn:ietf:params:oauth:grant-type:pre-authorized_code":
            "pre-authorized_code": generate
            tx_code:
              code: wall13
              input_mode: text
              length: 6
              description: PIN
        credentialDataSupplierInput: "{{ base_itb_data.abc}}"         
        credentialMetadata:
          expiration: 2678400
    - name: GC_STAT
      description: Issuance of a Generic Credential with IETF status list information
      url: "{{ protocol }}:{{ basedomain }}/sandbox"
      token: "{{ tokens.sandbox.admin }}"
      data:
        credentials:
          - GenericCredential_JWT
        grants:
          "urn:ietf:params:oauth:grant-type:pre-authorized_code":
            "pre-authorized_code": generate
        credentialDataSupplierInput: "{{ base_itb_data.gc}}"         
        credentialMetadata:
          expiration: 2678400
          enableStatusLists: true
    - name: ABC_STAT
      description: Issuance of a Academic Base Credential with Bitstring status list information
      url: "{{ protocol }}:{{ basedomain }}/sandbox"
      token: "{{ tokens.sandbox.admin }}"
      data:
        credentials:
          - AcademicBaseCredential_JWT
        grants:
          "urn:ietf:params:oauth:grant-type:pre-authorized_code":
            "pre-authorized_code": generate
        credentialDataSupplierInput: "{{ base_itb_data.abc}}"         
        credentialMetadata:
          expiration: 2678400
          enableStatusLists: true
    - name: ABC_JWT
      description: Issuance of a Academic Base Credential in VCDM JWT_VC_JSON format
      url: "{{ protocol }}:{{ basedomain }}/sandbox"
      token: "{{ tokens.sandbox.admin }}"
      data:
        credentials:
          - AcademicBaseCredential_JWT
        grants:
          "urn:ietf:params:oauth:grant-type:pre-authorized_code":
            "pre-authorized_code": generate
        credentialDataSupplierInput: "{{ base_itb_data.abc}}"         
        credentialMetadata:
          expiration: 2678400
          enableStatusLists: false
    - name: ABC_LD
      description: Issuance of a Academic Base Credential in VCDM JWT_VC_JSON format with embedded LD proof
      url: "{{ protocol }}:{{ basedomain }}/sandbox"
      token: "{{ tokens.sandbox.admin }}"
      data:
        credentials:
          - AcademicBaseCredential_LD
        grants:
          "urn:ietf:params:oauth:grant-type:pre-authorized_code":
            "pre-authorized_code": generate
        credentialDataSupplierInput: "{{ base_itb_data.abc}}"         
        credentialMetadata:
          expiration: 2678400
          enableStatusLists: false
    - name: ABC_SD
      description: Issuance of a Academic Base Credential in SD-JWT format
      url: "{{ protocol }}:{{ basedomain }}/sandbox"
      token: "{{ tokens.sandbox.admin }}"
      data:
        credentials:
          - AcademicBaseCredential_SD
        grants:
          "urn:ietf:params:oauth:grant-type:pre-authorized_code":
            "pre-authorized_code": generate
        credentialDataSupplierInput: "{{ base_itb_data.abc}}"         
        credentialMetadata:
          expiration: 2678400
          enableStatusLists: false
