#
---
- hosts: all
  roles:
    - { role: basic, tags: ['basic'] }
    - { role: clone_repo, tags: ['clone'] }
    - { role: copy_files, tags: ['copy', 'install'] }
    - { role: build, tags: ['build', 'install'] }
    - { role: post_config, tags: ['post-config', 'install'] }
    - { role: run_docker, tags: ['docker', 'run'] }
    - { role: test_install, tags: ['test']}
