#
---
- hosts: all
  roles:
    - { role: basic, tags: ['basic', 'install'] }
    - { role: clone_repo, tags: ['clone', 'install'] }
    - { role: copy_files, tags: ['copy', 'install'] }
    - { role: run_docker, tags: ['docker', 'run'] }
