#!/bin/bash
set -e

ansible-galaxy collection install community.docker

declare -a ansible_args
if [[ ! "x$DEBUG" = "x" ]]
then
    set -x
    ansible_args+=("-vvv")
fi

PROV="agent"
INV="eduwallet"
if [[ ! "x$1" = "x" ]]
then
    INV=$1
    shift
fi

while [ $# -gt 0 ]
do
    arg=$1
    shift
    ansible_args+=($arg)
done

# if ANSIBLE_BECOME_PASS is set and not empty, use it instead of the -K flag
if [[ ! "x$ANSIBLE_BECOME_PASS" = "x" ]]
then
  ansible_args+=("--extra-vars")
  ansible_args+=("ansible_become_pass=$ANSIBLE_BECOME_PASS")
else
  echo "ANSIBLE_BECOME_PASS env is not set, prompting for BECOME password"
  ansible_args+=("-K")
fi

ansible_args+=("-i")
ansible_args+=("environments/$INV/inventory")

# all systems currently seem to have python3 installed
#ansible_args+=("--extra-vars")
#ansible_args+=("ansible_python_interpreter=/usr/bin/python3")
ansible_args+=("--vault-password-file")
ansible_args+=("./ansible_vault_id")
ansible_args+=("$PROV.yml")

#export ANSIBLE_DEBUG=1
echo "ansible-playbook  ${ansible_args[*]}"
ansible-playbook  ${ansible_args[*]}
