#!/bin/bash
set -e

ansible-galaxy collection install community.docker

declare -a ansible_args
if [[ ! "x$DEBUG" = "x" ]]
then
    set -x
    ansible_args+=("-vvv")
fi

PROV="agent"

if [[ "x$INV" = "x" ]]
then
  if [[ "x$1" = "x" ]]
  then
    # Inv not provided via INV or argument
    echo "set \$INV or provide as argument"
    echo "Usage: $0 <inventory>"
    echo "  inventory: the name of the inventory to use."
    echo "valid values are eduwallet or edubadges"
    exit 1
  else
    # Inv provided as argument
    INV=$1
    shift
  fi
fi

echo "Using inventory: environments/$INV/inventory"

while [ $# -gt 0 ]
do
    arg=$1
    shift
    ansible_args+=($arg)
done

# if ANSIBLE_BECOME_PASS is set and not empty, use it instead of the -K flag
if [[ ! "x$ANSIBLE_BECOME_PASS" = "x" ]]
then
  ansible_args+=("--extra-vars")
  ansible_args+=("ansible_become_pass=$ANSIBLE_BECOME_PASS")
else
  echo "ANSIBLE_BECOME_PASS env is not set, prompting for BECOME password"
  ansible_args+=("-K")
fi

ansible_args+=("-i")
ansible_args+=("environments/$INV/inventory.yml")

# all systems currently seem to have python3 installed
#ansible_args+=("--extra-vars")
#ansible_args+=("ansible_python_interpreter=/usr/bin/python3")
ansible_args+=("--vault-password-file")
ansible_args+=("./ansible_vault_id")
ansible_args+=("$PROV.yml")

#export ANSIBLE_DEBUG=1
echo "ansible-playbook  ${ansible_args[*]}"
ansible-playbook  ${ansible_args[*]}
