---
- name: Verifier - Ensure the Dids configuration directories exists
  file:
    state: directory
    path: "{{ verifier.dir }}/conf/dids"
    mode: 0755
  become: yes
  when: enableverifier

- name: Verifier - Clean did configurations
  ansible.builtin.shell:
    cmd: "rm -f {{ verifier.dir }}/conf/dids/*.json"
  become: yes

- name: Verifier - Install verifier DID specifications
  template:
    src: didkey.json.j2
    dest: "{{ verifier.dir }}/conf/dids/{{ instance.name }}.json"
  loop: "{{ verifier_dids }}"
  loop_control:
    loop_var: instance
  become: yes
  when: enableverifier

- name: Verifier - Check DID specifications
  ansible.builtin.shell:
    cmd: "cat {{ verifier.dir }}/conf/dids/{{ instance.name }}.json | jq '.' > tmp;mv tmp {{ verifier.dir }}/conf/dids/{{ instance.name }}.json"
    chdir: "{{ docker.dir }}"
  loop: "{{ verifier_dids }}"
  loop_control:
    loop_var: instance
  become: yes

- name: Ensure the Presentation configuration directory exists
  file:
    state: directory
    path: "{{ verifier.dir }}/conf/presentations"
    mode: 0755
  become: yes
  when: enableverifier

- name: Clean presentation definitions
  ansible.builtin.shell:
    cmd: "rm -f {{ verifier.dir }}/conf/presentations/*.json"
    chdir: "{{ docker.dir }}"
  become: yes
  when: enableverifier

- name: Install presentation definitions
  template:
    src: "{{ instance.template }}"
    dest: "{{ verifier.dir }}/conf/presentations/{{ instance.id }}.json"
  loop: "{{ presentation_configurations }}"
  loop_control:
    loop_var: instance
  become: yes
  when: enableverifier

- name: Check presentation definitions
  ansible.builtin.shell:
    cmd: "cat {{ verifier.dir }}/conf/presentations/{{ instance.id }}.json | jq '.' > tmp;mv tmp {{ verifier.dir }}/conf/presentations/{{ instance.id }}.json"
    chdir: "{{ docker.dir }}"
  loop: "{{ presentation_configurations }}"
  loop_control:
    loop_var: instance
  become: yes
  when: enableverifier

- name: Push Verifier Env file
  template:
    src: verifier.env.j2
    dest: "{{ verifier.dir }}/.env"
  become: yes
  when: enableverifier

- name: Ensure the Verifiers configuration directory exists
  file:
    state: directory
    path: "{{ verifier.dir }}/conf/verifiers"
    mode: 0755
  become: yes
  when: enableverifier

- name: Clean verifier configurations
  ansible.builtin.shell:
    cmd: "rm -f {{ verifier.dir }}/conf/verifiers/*.json"
    chdir: "{{ docker.dir }}"
  become: yes
  when: enableverifier

- name: Install verifier configurations
  template:
    src: verifier.json.j2
    dest: "{{ verifier.dir }}/conf/verifiers/{{ instance.name }}.json"
  loop: "{{ verifiers }}"
  loop_control:
    loop_var: instance
  become: yes
  when: enableverifier

- name: Check verifier configurations
  ansible.builtin.shell:
    cmd: "cat {{ verifier.dir }}/conf/verifiers/{{ instance.name }}.json | jq '.' > tmp;mv tmp {{ verifier.dir }}/conf/verifiers/{{ instance.name }}.json"
    chdir: "{{ docker.dir }}"
  loop: "{{ verifiers }}"
  loop_control:
    loop_var: instance
  become: yes
  when: enableverifier
