- name: Create configuration file structure based on environment variables and env file content
  ansible.builtin.shell:
    cmd: python ./generate.py
    chdir: "{{ configuration.dir }}"
  become: true

- name: Ensure Issuer configuration directory exists
  file:
    state: directory
    path: "{{ agent.dir }}/conf"
    mode: 0755
  become: true

- name: Copy the Issuer configuration
  ansible.builtin.shell:
    cmd: "cp -darp {{ configuration.dir }}/dist/issuer/* {{ agent.dir }}/conf"
    chdir: "{{ configuration.dir }}"
  become: true

- name: Ensure Verifier configuration directory exists
  file:
    state: directory
    path: "{{ verifier.dir }}/conf"
    mode: 0755
  become: true

- name: Copy the Verifier configuration
  ansible.builtin.shell:
    cmd: "cp -darp {{ configuration.dir }}/dist/verifier/* {{ verifier.dir }}/conf"
    chdir: "{{ configuration.dir }}"
  become: true

- name: Ensure StatusList configuration directory exists
  file:
    state: directory
    path: "{{ statuslists.dir }}/conf"
    mode: 0755
  become: true
  when: statuslists.enabled

- name: Copy the StatusList configuration
  ansible.builtin.shell:
    cmd: "cp -darp {{ configuration.dir }}/dist/statuslist/* {{ statuslists.dir }}/conf"
    chdir: "{{ configuration.dir }}"
  become: true
  when: statuslists.enabled

- name: Ensure ITB configuration directory exists
  file:
    state: directory
    path: "{{ itb.dir }}/conf"
    mode: 0755
  become: true
  when: itb.enabled

- name: Copy the ITB configuration
  ansible.builtin.shell:
    cmd: "cp -darp {{ configuration.dir }}/dist/itb/* {{ itb.dir }}/conf"
    chdir: "{{ configuration.dir }}"
  become: true
  when: itb.enabled
