---
- name: Ensure database directory exists
  file:
    state: directory
    path: "{{ database.dir }}"
    mode: 0755
  become: true

# disabled, because we clean up the code now after build
#- name: Prebuilding all docker containers
#  ansible.builtin.shell:
#    cmd: "docker compose -p {{ compose_project }} build"
#    chdir: "{{ docker.dir }}"
#  become: true

- name: Stop the existing setup
  ansible.builtin.shell:
    cmd: docker compose -p {{ compose_project }} down
    chdir: "{{ docker.dir }}"
  become: true

- name: Pruning stopped containers
  ansible.builtin.shell:
    cmd: docker container prune -f
    chdir: "{{ docker.dir }}"
  become: true

- name: Pruning unused images
  ansible.builtin.shell:
    cmd: docker image prune -f
    chdir: "{{ docker.dir }}"
  become: true

- name: Run the docker containers using docker-compose
  community.docker.docker_compose_v2:
    project_src: "{{ docker.dir }}"
    project_name: "{{ compose_project }}"
    state: present
  become: true

- name: Wait for the certificate to settle
  ansible.builtin.uri:
    url: "{{ protocol }}://{{ basedomain }}/mbob/.well-known/openid-credential-issuer"
    follow_redirects: none
    method: GET
  register: _result
  until: _result.status == 200
  retries: 720 # 720 * 5 seconds = 1hour (60*60/5)
  delay: 5 

