---
- name: Install DID configuration
  include_tasks: dids.yml

- name: Install Credentials configuration
  include_tasks: credential_configurations.yml

- name: Ensure the Agent configuration directories exists
  file:
    state: directory
    path: "{{ agent.dir }}/conf/{{ item }}"
    mode: 0755
  loop:
    - issuer
    - metadata
  become: yes

- name: Push Agent Env file
  template:
    src: agent.env.j2
    dest: "{{ agent.dir }}/.env"
  become: yes

- name: Clean issuer configurations
  ansible.builtin.shell:
    cmd: "rm {{ agent.dir }}/conf/issuer/*.json"
    chdir: "{{ docker.dir }}"
  become: yes

- name: Install issuer configurations
  template:
    src: issuer.json.j2
    dest: "{{ agent.dir }}/conf/issuer/{{ instance.name }}.json"
  loop: "{{ installations }}"
  loop_control:
    loop_var: instance
  become: yes

- name: Check issuer configuration
  ansible.builtin.shell:
    cmd: "cat {{ agent.dir }}/conf/issuer/{{ instance.name }}.json | jq '.' > tmp;mv tmp {{ agent.dir }}/conf/issuer/{{ instance.name }}.json"
    chdir: "{{ docker.dir }}"
  loop: "{{ installations }}"
  loop_control:
    loop_var: instance
  become: yes

- name: Clean metadata configurations
  ansible.builtin.shell:
    cmd: "rm {{ agent.dir }}/conf/metadata/*.json"
    chdir: "{{ docker.dir }}"
  become: yes

- name: Install metadata configurations
  template:
    src: metadata.json.j2
    dest: "{{ agent.dir }}/conf/metadata/{{ instance.name }}.json"
  loop: "{{ installations }}"
  loop_control:
    loop_var: instance
  become: yes

- name: Check metadata configuration
  ansible.builtin.shell:
    cmd: "cat {{ agent.dir }}/conf/metadata/{{ instance.name }}.json | jq '.' > tmp;mv tmp {{ agent.dir }}/conf/metadata/{{ instance.name }}.json"
    chdir: "{{ docker.dir }}"
  loop: "{{ installations }}"
  loop_control:
    loop_var: instance
  become: yes

    