---
- name: Agent - Ensure the Context configuration directories exists
  file:
    state: directory
    path: "{{ agent.dir }}/conf/contexts"
    mode: 0755
  become: yes

- name: Clean configurations
  ansible.builtin.shell:
    cmd: "rm -f {{ agent.dir }}/conf/contexts/*.json"
    chdir: "{{ docker.dir }}"
  become: yes

- name: Agent - Install contexts
  template:
    src: "{{ instance.src }}"
    dest: "{{ agent.dir }}/conf/contexts/{{ instance.dest }}"
  loop: "{{ contexts }}"
  loop_control:
    loop_var: instance
  become: yes

- name: Agent - Check context configurations
  ansible.builtin.shell:
    cmd: "cat {{ agent.dir }}/conf/contexts/{{ instance.dest }} | jq '.' > tmp;mv tmp {{ agent.dir }}/conf/contexts/{{ instance.dest }}"
    chdir: "{{ docker.dir }}"
  loop: "{{ contexts }}"
  loop_control:
    loop_var: instance
  become: yes
