---
- name: Ensure the Credentials configuration directory exists
  file:
    state: directory
    path: "{{ agent.dir }}/conf/credentials"
    mode: 0755
  become: yes

- name: Install credential specifications
  template:
    src: "{{ instance.template }}"
    dest: "{{ agent.dir }}/conf/credentials/{{ instance.name }}.json"
  loop: "{{ credential_configurations }}"
  loop_control:
    loop_var: instance
  become: yes

- name: Check credential specifications
  ansible.builtin.shell:
    cmd: "cat {{ agent.dir }}/conf/credentials/{{ instance.name }}.json | jq '.' > tmp;mv tmp {{ agent.dir }}/conf/credentials/{{ instance.name }}.json"
    chdir: "{{ docker.dir }}"
  loop: "{{ credential_configurations }}"
  loop_control:
    loop_var: instance
  become: yes
