---
- name: Ensure the Dids configuration directories exists
  file:
    state: directory
    path: "{{ agent.dir }}/conf/dids"
    mode: 0755
  become: yes

- name: Install issuer DID specifications
  template:
    src: did.json.j2
    dest: "{{ agent.dir }}/conf/dids/{{ instance.name }}.json"
  loop: "{{ dids }}"
  loop_control:
    loop_var: instance
  become: yes

- name: Check DID specifications
  ansible.builtin.shell:
    cmd: "cat {{ agent.dir }}/conf/dids/{{ instance.name }}.json | jq '.'"
    chdir: "{{ docker.dir }}"
  loop: "{{ dids }}"
  loop_control:
    loop_var: instance
  become: yes
