---
- name: Agent - Ensure the Dids configuration directories exists
  file:
    state: directory
    path: "{{ agent.dir }}/conf/dids"
    mode: 0755
  become: yes

- name: Clean did configurations
  ansible.builtin.shell:
    cmd: "rm -f {{ agent.dir }}/conf/dids/*.json"
    chdir: "{{ docker.dir }}"
  become: yes

- name: Agent - Install issuer DID specifications
  template:
    src: did.json.j2
    dest: "{{ agent.dir }}/conf/dids/{{ instance.name }}.json"
  loop: "{{ dids }}"
  loop_control:
    loop_var: instance
  become: yes

- name: Agent - Check DID specifications
  ansible.builtin.shell:
    cmd: "cat {{ agent.dir }}/conf/dids/{{ instance.name }}.json | jq '.' > tmp;mv tmp {{ agent.dir }}/conf/dids/{{ instance.name }}.json"
    chdir: "{{ docker.dir }}"
  loop: "{{ dids }}"
  loop_control:
    loop_var: instance
  become: yes

