- name: Ensure Docker directory exists
  file:
    state: directory
    path: "{{ docker.dir }}"
    mode: 0755
  become: true

- name: Ensure Issuer directory exists
  file:
    state: directory
    path: "{{ docker.dir }}/issuer"
    mode: 0755
  become: true

- name: Copy generic Dockerfile for issuer
  ansible.builtin.shell:
    cmd: "cp {{ configuration.dir }}/Dockerfile {{ docker.dir }}/issuer/"
  become: yes

- name: Remove Issuer configuration
  ansible.builtin.shell:
    cmd: "rm -rf {{ docker.dir }}/issuer/conf"
  become: yes

- name: Copy Issuer configuration
  ansible.builtin.shell:
    cmd: "/usr/bin/cp -fr {{ configuration.dir }} {{ docker.dir }}/issuer/conf"
  become: yes

- name: Ensure Verifier directory exists
  file:
    state: directory
    path: "{{ docker.dir }}/verifier"
    mode: 0755
  become: true

- name: Copy generic Dockerfile for verifier
  ansible.builtin.shell:
    cmd: "cp {{ configuration.dir }}/Dockerfile {{ docker.dir }}/verifier/"
  become: yes

- name: Remove Verifier configuration
  ansible.builtin.shell:
    cmd: "rm -rf {{ docker.dir }}/verifier/conf"
  become: yes

- name: Copy Verifier configuration
  ansible.builtin.shell:
    cmd: "/usr/bin/cp -fr {{ configuration.dir }} {{ docker.dir }}/verifier/conf"
  become: yes

- name: Remove Statuslist configuration
  ansible.builtin.shell:
    cmd: "rm -rf {{ docker.dir }}/statuslists/conf"
  become: yes
  when: itb.enabled

- name: Copy configuration
  ansible.builtin.shell:
    cmd: "/usr/bin/cp -fr {{ configuration.dir }} {{ docker.dir }}/statuslists/conf"
  become: yes

- name: Ensure ITB directory exists
  file:
    state: directory
    path: "{{ docker.dir }}/itb"
    mode: 0755
  become: true

- name: Remove ITB configuration
  ansible.builtin.shell:
    cmd: "rm -rf {{ docker.dir }}/itb/conf"
  become: yes
  when: itb.enabled

- name: Copy ITB configuration
  ansible.builtin.shell:
    cmd: "/usr/bin/cp -fr {{ configuration.dir }} {{ docker.dir }}/itb/conf"
  become: yes
  when: itb.enabled

- name: Copy manager Dockerfile
  ansible.builtin.template:
    src: dockerfile_manager.j2
    dest: "{{ docker.dir }}/manager/Dockerfile"
  become: yes
  when: itb.enabled

- name: Push Docker Env file
  template:
    src: docker.env.j2
    dest: "{{ docker.dir }}/.env"
  become: true

- name: Push Docker Compose configuration
  template:
    src: docker-compose.yml.j2
    dest: "{{ docker.dir }}/docker-compose.yml"
  become: true
