---
- name: Install Issuer env file
  template:
    src: env.agent.j2
    dest: "{{ agent.dir }}/.env"
  become: yes

- name: Install Verifier env file
  template:
    src: env.verifier.j2
    dest: "{{ verifier.dir }}/.env"
  become: yes

- name: Install ITB env file
  template:
    src: env.itb.j2
    dest: "{{ itb.dir }}/.env"
  become: yes
  when: itb.enabled

- name: Install Configuration env file
  template:
    src: env.configuration.j2
    dest: "{{ configuration.dir }}/.env"
  become: yes

- name: Ensure static directory exists
  file:
    state: directory
    path: "{{ static.dir }}/vct"
    mode: 0755
  become: true
  when: static.enabled

- name: Run configuration generator to apply replacements
  ansible.builtin.command:
    cmd: "python3 {{ configuration.dir }}/generate.py --input {{ configuration.dir }} --output {{ configuration.dir }}/dist"
  become: yes
  when: static.enabled

- name: Copy Institution Card Credential vct
  ansible.builtin.shell:
    cmd: "cp {{ configuration.dir }}/dist/issuer/mbobauth/vct/InstitutionCardCredential.json {{ static.dir }}/vct/institutioncardcredential"
  become: yes
  when: static.enabled
