- name: "{{ installation.name }}: Ensure Issuer directory exists"
  file:
    state: directory
    path: "{{ docker.dir }}/issuer/{{ installation.name }}"
    mode: 0755
  become: true

- name: "{{ installation.name }}: Copy generic Dockerfile for issuer"
  ansible.builtin.shell:
    cmd: "cp {{ configuration.dir }}/Dockerfile {{ docker.dir }}/issuer/{{ installation.name }}/"
  become: yes

- name: "{{ installation.name }}: Copy generate.py to the Dockerfile context"
  ansible.builtin.shell:
    cmd: "cp {{ configuration.dir }}/generate.py {{ docker.dir }}/issuer/{{ installation.name }}/"
  become: yes

- name: "{{ installation.name }}: Copy docker-entrypoint.sh to the Dockerfile context"
  ansible.builtin.shell:
    cmd: "cp {{ configuration.dir }}/docker-entrypoint.sh {{ docker.dir }}/issuer/{{ installation.name }}/"
  become: yes

- name: "{{ installation.name }}: Remove Issuer configuration"
  ansible.builtin.shell:
    cmd: "rm -rf {{ docker.dir }}/issuer/{{ installation.name }}/conf"
  become: yes

- name: "{{ installation.name }}: Copy Issuer configuration"
  ansible.builtin.shell:
    cmd: "cp -fr {{ configuration.dir }}/issuer/{{ installation.name }} {{ docker.dir }}/issuer/{{ installation.name }}/conf"
  become: yes

- name: "{{ installation.name }}: Remove Issuer app source"
  ansible.builtin.shell:
    cmd: "rm -rf {{ docker.dir }}/issuer/{{ installation.name }}/app"
  become: yes

- name: "{{ installation.name }}: Copy Issuer app source"
  ansible.builtin.shell:
    cmd: "cp -fr {{ agent.dir }} {{ docker.dir }}/issuer/{{ installation.name }}/app"
  become: yes
