---
- name: Install Docker configuration
  include_tasks: docker.yml

- name: Install Agent configuration
  include_tasks: agent.yml

- name: Install ITB configuration
  include_tasks: itb.yml
  when: itb.enabled

- name: Ensure the OpenObserver log directory exists
  file:
    state: directory
    path: "{{ openobserver.datadir }}"
    mode: 0755
  become: yes

