---
- name: Loop over all installed configurations
  include_tasks: test_install.yml
  loop: "{{ installations }}"
  loop_control:
    loop_var: installation

- name: Loop over the verifier installations
  include_tasks: test_verifier.yml
  loop: "{{ verifiers }}"
  loop_control:
    loop_var: installation
  when: enableverifier

- name: Loop over the statuslist installations
  include_tasks: test_statlist.yml
  loop: "{{ statuslists.installations }}"
  loop_control:
    loop_var: installation
  when: statuslists.enabled
