---
- name: "{{ installation.name }}: Testing well knowns - openid-credential-issuer"
  ansible.builtin.uri:
    url: "{{ protocol }}://{{ basedomain }}/{{ installation.name }}/.well-known/openid-credential-issuer"
    method: GET

- name: "{{ installation.name }}: Testing well knowns - did:web"
  ansible.builtin.uri:
    url: "{{ protocol }}://{{ basedomain }}/{{ installation.name }}/.well-known/did.json"
    method: GET

- name: "{{ installation.name }}: Testing well knowns - openid-configuration"
  ansible.builtin.uri:
    url: "{{ protocol }}://{{ basedomain }}/{{ installation.name }}/.well-known/openid-configuration"
    method: GET

- name: "{{ installation.name }}: Testing well knowns - oauth-authorization-server"
  ansible.builtin.uri:
    url: "{{ protocol }}://{{ basedomain }}/{{ installation.name }}/.well-known/oauth-authorization-server"
    method: GET

- name: "{{ installation.name }}: Testing create offer"
  ansible.builtin.uri:
    url: "{{ protocol }}://{{ basedomain }}/{{ installation.name }}/api/create-offer"
    body_format: json
    headers:
      Content-type: 'application/json'
      Authorization: "Bearer {{ installation.adminToken }}"
    body: "{\"credentials\":[\"{{ installation.credential }}\"],\"grants\":{\"urn:ietf:params:oauth:grant-type:pre-authorized_code\":{\"pre-authorized_code\":\"{{ installation.preauthcode }}\",\"user_pin_required\":false}},\"credentialDataSupplierInput\":{\"organization\":\"a\",\"personName\":\"b\",\"emailAddress\":\"a@b.nl\",\"affiliation\":\"student\"}}"
    method: POST

- name: "{{ installation.name }}: Testing get offer"
  ansible.builtin.uri:
    url: "{{ protocol }}://{{ basedomain }}/{{ installation.name }}/get-credential-offer/{{ installation.preauthcode}}"
    method: GET

- name: "{{ installation.name }}: Testing check offer"
  ansible.builtin.uri:
    url: "{{ protocol }}://{{ basedomain }}/{{ installation.name }}/api/check-offer"
    body_format: json
    body: "{\"id\":\"{{ installation.preauthcode}}\"}"
    method: POST

