---
- name: "{{ installation.name }}: Testing create authorization
  ansible.builtin.uri:
    url: "{{ protocol }}://{{ verifierdomain }}{{ installation.path }}/api/create-offer"
    body_format: json
    headers:
      Content-type: 'application/json'
      Authorization: "Bearer {{ installation.adminToken }}"
    body: "'{}'"
    method: POST

- name: "{{ installation.name }}: Testing get offer"
  ansible.builtin.uri:
    url: "{{ protocol }}://{{ verifierdomain }}{{ installation.path }}/api/get-credential-offer/{{ installation.preauthcode}}"
    method: GET

