---
- name: Clone the Verifier Deploy repository
  ansible.builtin.git:
    repo: "{{ sources.verifierdeploy.repo }}"
    dest: "{{ verifierdeploy.dir }}"
    version: "{{ sources.verifierdeploy.version }}"
    force: yes
  become: yes

- name: Build and configure installations
  include_tasks: installtasks.yml
  loop: "{{ verifierdeploy.installations }}"
  loop_control:
    loop_var: deploy

